### ISSUE TITLE
Docs: How to use the MAS admin-api

### ISSUE THREAD

**Issue by hanthor** [element-hq/ess-helm#354]
I migrated a matrix-docker-ansible-deployment  with MAS already enabled. MAS wouldn't allow me to re-provision my account in mas gave me the error `Username not available on homeserver`

made a `masadminapi.yaml`
```
matrixAuthenticationService:
  additional:
    0-adminClient:
      config: |
        policy:
          data:
            admin_clients:
              - 0000000000000000000SYNAPSE
```

and added it to my helm upgrade command with `-f ~/ess-config-values/mas.yaml`

Then I performed the curl command from the synapse pod in bash with `kubectl exec -n ess -it statefulset/ess-synapse-main -- bash`:

```
CLIENT_ID=0000000000000000000SYNAPSE \
CLIENT_SECRET=CHANGEME \
curl \
  -u "0000000000000000000SYNAPSE:$CLIENT_SECRET" \
  -d "grant_type=client_credentials&scope=urn:mas:admin" \
  http://ess-matrix-authentication-service.ess.svc.cluster.local:8080/oauth2/token 
```

Then copy in the access token into the next command:

```
curl -X 'POST' \
  -H "Authorization: Bearer mat_CHANGEME" \
  'http://ess-matrix-authentication-service.ess.svc.cluster.local:8080/api/admin/v1/users' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "james",
  "skip_homeserver_check": true
}'
```

Then I set a password with:

`kubectl exec -n ess -it deploy/ess-matrix-authentication-service -- mas-cli manage set-password james supersecretpassword`
