### ISSUE TITLE
Secrets key adding

### ISSUE THREAD

**Issue by eduard-unplugged** [element-hq/ess-helm#355]
**Describe the bug**
Pulled: ghcr.io/element-hq/ess-helm/matrix-stack:0.9.0
Digest: sha256:7bdc918ae1dfc937bdbc2600c31d7487a7d083a0b6cdb5c601effeaa41fdcdc2
Error: template: matrix-stack/templates/synapse/synapse_statefulset.yaml:22:35: executing "matrix-stack/templates/synapse/synapse_statefulset.yaml" at <include (print $.Template.BasePath "/synapse/synapse_secret.yaml") $>: error calling include: template: matrix-stack/templates/synapse/synapse_secret.yaml:17:4: executing "matrix-stack/templates/synapse/synapse_secret.yaml" at <include "element-io.synapse.secret-data" (dict "root" $ "context" .)>: error calling include: template: matrix-stack/templates/synapse/_synapse_secret.tpl:27:37: executing "element-io.synapse.secret-data" at <b64enc>: wrong type for value; expected string; got map[string]interface {}

When config is: 
  signingKey: {}
  registrationSharedSecret: 
    value: my key
  macaroon: 
    value: my key

**To Reproduce**
helm upgrade -n synapse --install ess oci://ghcr.io/element-hq/ess-helm/matrix-stack -f values.yaml

**Expected behavior**
installation

**Additional information:**
 - AWS EKS 1.30

**Comment by gaelgatelement** [comment]
Hello @eduard-unplugged 

Is `initSecrets` disabled ?

Could you provider your values file with secrets censored ?
Thanks

**Comment by eduard-netoplayltd** [comment]
> Hello [@eduard-unplugged](https://github.com/eduard-unplugged)
> 
> Is `initSecrets` disabled ?
> 
> Could you provider your values file with secrets censored ? Thanks

```
  registrationSharedSecret:
    secret: synapse-secrets
    secretKey: registrationSharedSecret

  macaroon:
    secret: synapse-secrets
    secretKey: macaroon

  signingKey:
    secret: synapse-secrets
    secretKey: signingKey

```
Just like that, i made secrets in cluster. and yes - initsecrets is disabled

**Comment by eduard-netoplayltd** [comment]
> > Hello [@eduard-unplugged](https://github.com/eduard-unplugged)
> > Is `initSecrets` disabled ?
> > Could you provider your values file with secrets censored ? Thanks
> 
> registrationSharedSecret: secret: synapse-secrets secretKey: registrationSharedSecret
> 
> macaroon: secret: synapse-secrets secretKey: macaroon
> 
> signingKey: secret: synapse-secrets secretKey: signingKey
> 
> Just like that, i made secrets in cluster. and yes - initsecrets is disabled

i also tryed just put the values, and do it with empty {}. and have issue or about mapping or about string

**Comment by eduard-netoplayltd** [comment]
Error: template: matrix-stack/templates/synapse/synapse_statefulset.yaml:22:35: executing "matrix-stack/templates/synapse/synapse_statefulset.yaml" at <include (print $.Template.BasePath "/synapse/synapse_secret.yaml") $>: error calling include: template: matrix-stack/templates/synapse/synapse_secret.yaml:17:4: executing "matrix-stack/templates/synapse/synapse_secret.yaml" at <include "element-io.synapse.secret-data" (dict "root" $ "context" .)>: error calling include: template: matrix-stack/templates/synapse/_synapse_secret.tpl:27:37: executing "element-io.synapse.secret-data" at <b64enc>: wrong type for value; expected string; got map[string]interface {}.   

This is with empty value

**Comment by gaelgatelement** [comment]
It looks like you need to place secrets below Synapse like in this example : https://github.com/element-hq/ess-helm/blob/main/charts/matrix-stack/ci/fragments/synapse-secrets-externally.yaml

**Comment by eduard-netoplayltd** [comment]
```
matrixTools:
  image:
    registry: ghcr.io
    repository: element-hq/ess-helm/matrix-tools
    tag: "0.3.3"
    pullSecrets: []
certManager: {}
serverName: matrix.app
labels: {}
ingress:
  annotations:
    alb.ingress.kubernetes.io/actions.response-503: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"503","messageBody":"Unknown Host"}}

    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}

    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:eu-west-2:076951083070:certificate/dd0aebbe-6761-4a80-b432-93c4f7b813d5
    alb.ingress.kubernetes.io/group.name: synapse
    alb.ingress.kubernetes.io/group.order: '1'
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true,idle_timeout.timeout_seconds=600
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
    alb.ingress.kubernetes.io/tags: Environment=Dev
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  tlsEnabled: false
  service:
    type: ClusterIP
imagePullSecrets: []
tolerations: []
topologySpreadConstraints: []
initSecrets:
  enabled: true
  rbac:
    create: true
  labels: {}
  containersSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 10010
    runAsGroup: 10010
    runAsNonRoot: true
    runAsUser: 10010
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups: []
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 200Mi
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  tolerations: []
elementWeb:
  enabled: false
  additional: {}
  replicas: 1
  image:
    registry: docker.io
    repository: vectorim/element-web
    tag: "v1.11.96"
    pullSecrets: []
  ingress:
    annotations: {}
    tlsEnabled: true
    service: {}
  labels: {}
  extraEnv: []
  containersSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 10004
    runAsGroup: 10004
    runAsNonRoot: true
    runAsUser: 10004
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups: []
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 200Mi
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  tolerations: []
  topologySpreadConstraints: []
haproxy:
  replicas: 1
  image:
    registry: docker.io
    repository: library/haproxy
    tag: "3.1-alpine"
    pullSecrets: []
  labels: {}
  containersSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups: []
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  serviceMonitors:
    enabled: true
  tolerations: []
  topologySpreadConstraints: []
matrixAuthenticationService:
  enabled: false
  image:
    registry: ghcr.io
    repository: element-hq/matrix-authentication-service
    tag: "0.14.0"
    pullSecrets: []
  postgres: {}
  encryptionSecret: {}
  synapseSharedSecret: {}
  synapseOIDCClientSecret: {}
  additional: {}
  privateKeys:
    rsa: {}
    ecdsaPrime256v1: {}
    ecdsaSecp256k1: {}
    ecdsaSecp384r1: {}
  ingress:
    annotations: {}
    tlsEnabled: true
    service: {}
  labels: {}
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  tolerations: []
  topologySpreadConstraints: []
  podSecurityContext:
    fsGroup: 10005
    runAsGroup: 10005
    runAsNonRoot: true
    runAsUser: 10005
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups: []
  containersSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  serviceMonitors:
    enabled: true
  extraEnv: []
postgres:
  enabled: false
  postgresExporter:
    image:
      registry: docker.io
      repository: prometheuscommunity/postgres-exporter
      tag: "v0.17.0"
      pullSecrets: []
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 500Mi
    containersSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  adminPassword: {}
  essPasswords:
    synapse: {}
    matrixAuthenticationService: {}
  storage:
    size: 10Gi
  image:
    registry: docker.io
    repository: postgres
    tag: "17-alpine"
    pullSecrets: []
  labels: {}
  containersSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 10091
    runAsGroup: 10091
    runAsNonRoot: true
    runAsUser: 10091
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups: []
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 4Gi
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  serviceMonitors:
    enabled: true
  tolerations: []
  topologySpreadConstraints: []
synapse:
  enabled: true
  checkConfigHook:
    enabled: true
    labels: {}
    serviceAccount:
      create: true
      name: ""
      annotations: {}
  postgres:
    host: host
    port: 5432
    user: synapse
    database: synapse
    password:
      value: r00t
  media:
    storage:
      size: 10Gi
    maxUploadSize: 100M
  registrationSharedSecret:
    secret: ess-synapse-external
    secretKey: registrationSharedSecret
  macaroon:
    secret: ess-synapse-external
    secretKey: macaroon
  signingKey:
    secret: ess-synapse-external
    secretKey: signingKey
  additional:
    jwt_config:
      config:
        enabled: true
        secret: |
          -----BEGIN RSA PUBLIC KEY-----
          
          -----END RSA PUBLIC KEY-----
        algorithm: RS256
        subject_claim: preferred_username
        audiences:
          - account
          - realm-management
    turn_uris:
      config:
        - turn:host?transport=udp
    turn_secret:
      config: "=977"
    turn_allow_guests:
      config: true
    password_config:
      config:
        enabled: true
        policy:
          minimum_length: 8
          require_uppercase: true
          require_digits: true
          require_special_characters: false
    rc_login:
      config:
        address:
          per_second: 10
          burst_count: 20
        account:
          per_second: 10
          burst_count: 20
    encryption_enabled_by_default_for_room_type:
      config: "all"
    experimental_features:
      config:
        msc3266_enabled: true
        msc4222_enabled: true
    max_event_delay_duration:
      config: "24h"
  appservices: []
  workers:
    appservice:
      enabled: false
    background:
      enabled: false
    client-reader:
      enabled: false
      replicas: 1
    encryption:
      enabled: false
    event-creator:
      enabled: false
      replicas: 1
    event-persister:
      enabled: false
      replicas: 1
    federation-reader:
      enabled: false
      replicas: 1
    federation-sender:
      enabled: false
      replicas: 1
    initial-synchrotron:
      enabled: false
      replicas: 1
    media-repository:
      enabled: false
    presence-writer:
      enabled: false
    push-rules:
      enabled: false
    pusher:
      enabled: false
      replicas: 1
    receipts-account:
      enabled: false
    sliding-sync:
      enabled: false
      replicas: 1
    sso-login:
      enabled: false
    synchrotron:
      enabled: false
      replicas: 1
    typing-persister:
      enabled: false
    user-dir:
      enabled: false
  logging:
    rootLevel: INFO
    levelOverrides: {}
  image:
    registry: docker.io
    repository: matrixdotorg/synapse
    tag: "v1.127.1"
    pullSecrets: []
  ingress:
    host: matrix.unpluggedsystems.app
    annotations: {}
    tlsEnabled: false
    service: {}
  labels: {}
  containersSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  extraEnv: []
  hostAliases: []
  podSecurityContext:
    fsGroup: 10091
    runAsGroup: 10091
    runAsNonRoot: true
    runAsUser: 10091
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups: []
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 4Gi
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  serviceMonitors:
    enabled: true
  tolerations: []
  topologySpreadConstraints: []
  extraArgs: []
  redis:
    image:
      registry: docker.io
      repository: library/redis
      tag: "7.4-alpine"
      pullSecrets: []
    labels: {}
    containersSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    podSecurityContext:
      fsGroup: 10002
      runAsGroup: 10002
      runAsNonRoot: true
      runAsUser: 10002
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups: []
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 50Mi
    serviceAccount:
      create: true
      name: ""
      annotations: {}
    tolerations: []
wellKnownDelegation:
  enabled: true
  labels: {}
  ingress:
    annotations: {}
    tlsEnabled: true
    service: {}
  baseDomainRedirect:
    enabled: true
    url: ""
  additional:
    client: "{}"
    server: "{}"
    element: "{}"
    support: "{}"
```

```

helm upgrade --install ess oci://ghcr.io/element-hq/ess-helm/matrix-stack \
  --version 0.9.0 \                                          
  -f values.yaml \
  --namespace synapse
Release "ess" does not exist. Installing it now.
Pulled: ghcr.io/element-hq/ess-helm/matrix-stack:0.9.0
Digest: sha256:7bdc918ae1dfc937bdbc2600c31d7487a7d083a0b6cdb5c601effeaa41fdcdc2
Error: template: matrix-stack/templates/synapse/synapse_statefulset.yaml:22:35: executing "matrix-stack/templates/synapse/synapse_statefulset.yaml" at <include (print $.Template.BasePath "/synapse/synapse_secret.yaml") $>: error calling include: template: matrix-stack/templates/synapse/synapse_secret.yaml:17:4: executing "matrix-stack/templates/synapse/synapse_secret.yaml" at <include "element-io.synapse.secret-data" (dict "root" $ "context" .)>: error calling include: template: matrix-stack/templates/synapse/_synapse_secret.tpl:27:37: executing "element-io.synapse.secret-data" at <b64enc>: wrong type for value; expected string; got map[string]interface {}

```
Already tried
