### ISSUE TITLE
Node Affinity adding

### ISSUE THREAD

**Issue by eduard-unplugged** [element-hq/ess-helm#368]
**Is your feature request related to a problem? Please describe.**
So on my cluster i have nodes with public and private IP. And it will be great if you can add Node affinities to choose by node tag or/and label in values

**Describe the solution you'd like**
Just adding it like option will be enough like:

```yaml
elementWeb:
  enabled: true
  additional: {}
  replicas: 1
  image:
    registry: ghcr.io
    repository:
    tag: <WEB_DOCKER_TAG>
    pullSecrets: 
      - name: github-auth
  ingress:
    host: <WEBHOST>
    annotations: {}
    tlsEnabled: true
    service: {}
  labels: {}
  extraEnv: []
  containersSecurityContext:
    allowPrivilegeEscalation: true
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 10004
    runAsGroup: 10004
    runAsNonRoot: true
    runAsUser: 10004
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups: []
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 200Mi
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  tolerations: []
  topologySpreadConstraints: []
 PodAffinity[]
 NodeAffinity[]
 //     nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - Private 
                    ```
