### ISSUE TITLE
Add shraing key annotation to nodeports

### ISSUE THREAD

**Issue by suse-coder** [element-hq/ess-helm#414]
**Is your feature request related to a problem? Please describe.**
I use cilium gateway api, that has until this day only httproute support. For video and audio I need tcp and udp routes (that are not yet available in cilium gateway). Thats why there are nodeports that are created by the ess helm chart. But as I have cilium gateway configured (loadbalancer) I can currently only have one loadbalancer for that and not create a second one (for the nodeports) and have the same ip. To allow that one needs to have the annotation: 

https://docs.cilium.io/en/latest/network/lb-ipam/#sharing-keys

Sharing Keys
Services can share the same IP or set of IPs with other services. This is done by setting the lbipam.cilium.io/sharing-key annotation on the service. Services that have the same sharing key annotation will share the same IP or set of IPs. The sharing key is a string that can be any value.
```
apiVersion: v1
kind: Service
metadata:
  name: service-blue
  namespace: example
  labels:
    color: blue
  annotations:
    "lbipam.cilium.io/sharing-key": "1234"
spec:
  type: LoadBalancer
  ports:
  - port: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: service-red
  namespace: example
  labels:
    color: red
  annotations:
    "lbipam.cilium.io/sharing-key": "1234"
spec:
  type: LoadBalancer
  ports:
  - port: 2345

```
Please add in the helm chart the option to define and use the sharing key annotation.
