### ISSUE TITLE
MRTC fails connection when behind NAT and on private network

### ISSUE THREAD

**Issue by p-rintz** [element-hq/ess-helm#503]
**Describe the bug**
MRTC connection is not possible if the kubernetes cluster is run in a private network, while the public IP of the matrix server is not situated on the kubernetes host itself.

Topology:

Hetzner Host <- ESS VM <- Kubernetes Pods on the ESS VM

IP is available on the Hetzner Host.

The Kubernetes MRTC pod tries to communicate with the matrix pod and resolves the host "matrixserver.example" via a public DNS resolver. This leads it to try to communicate with the public ip, which is not meant to accessed on the private network. Thus, failing in reaching the matrix host.

My hostnames file for clarity:
```
elementWeb:
  ingress:
    host: chat.matrixserver.example
matrixAuthenticationService:
  ingress:
    host: account.matrixserver.example
matrixRTC:
  ingress:
    host: mrtc.matrixserver.example
serverName: matrixserver.example
synapse:
  ingress:
    host: matrix.matrixserver.example
```

My current workaround is a iptables DNAT rule:
```-A PREROUTING -d 111.111.111.111/32 -p tcp -m tcp --dport 443 -j DNAT --to-destination 192.168.22.4:443```

**To Reproduce**
1. Have Host with public ip and a public dns entry for the matrix server.
2. Install ESS with mrtc
3. Have element call fail due to the connection issue.

**Expected behavior**

It should either not ignore my hosts DNS server settings, and thus use a private DNS server which would point to the correct reverse proxy.

Or better yet, have the mrtc pod communicate directly with the matrix pod and not rely on my outside reverse proxy in communication.

**Comment by benbz** [comment]
> It should either not ignore my hosts DNS server settings, and thus use a private DNS server which would point to the correct reverse proxy.

The chart does no special setting of DNS. Possibly what you want here is the ability to configure `Pod.spec.dnsPolicy` and/or `Pod.spec.dnsConfig`, which would be a feature request of this chart.

What we do have in the chart today that should solve your problem is the ability to set `hostAliases`. Then you can inject override IPs for `matrixserver.example` and `matrix.matrixserver.example` to the correct IP address

> Or better yet, have the mrtc pod communicate directly with the matrix pod and not rely on my outside reverse proxy in communication.

This would be a feature request of https://github.com/element-hq/lk-jwt-service

**Comment by p-rintz** [comment]
Thanks for the quick response.

How would I configure the hostAliases in the chart?

**Comment by benbz** [comment]
```yaml
matrixRTC:
  hostAliases:
  - ip: 192.168.22.4
    hostnames:
    - matrixserver.example
    - matrix.matrixserver.example
```

Can be done for any component but `matrixRTC` is the one you need in this situation
