### ISSUE TITLE
How to configure Turn Server

### ISSUE THREAD

**Issue by michael-pisman** [element-hq/ess-helm#504]
Hi, I am a bit confused on how to configure synapse to use TURN server.

- Do I do configure Matrix MRTC as described in [livekit](https://docs.livekit.io/home/self-hosting/deployment/#domain-ssl-certificates-and-load-balancer) or the way it's described in [synapse docs](https://matrix-org.github.io/synapse/latest/turn-howto.html?highlight=turn#synapse-setup)?

- Is the embedded TURN server shipped with livekit available or do I need to use external server?

Can anyone provide an example?

Thanks!

**Comment by kodxana** [comment]
Gonna share my setup as I did that recently to setup the legacy call:
In mys case I created: ess-config-values/turn.yaml

```
synapse:
  additional:
    user-config.yaml:
      config: |
        turn_uris:
          - "turn:SERVERADRESS:3478?transport=udp"
          - "turn:SERVERADRESS:3478?transport=tcp"
        turn_shared_secret: ""
        turn_user_lifetime: 86400000
        turn_allow_guests: true
```

Then in deploy command add: -f ~/ess-config-values/turn.yaml

**Comment by kodxana** [comment]
Also from what I know ess-helm does not run TURN server so you needs setup own one.

**Comment by michael-pisman** [comment]
@kodxana, thank you. This is how I used to do it. **Looks like this way still works!**

I was confused by the new stack and assumed that since Matrix MRTC comes from Live Kit, it should come with the embedded TURN server. Some insight from maintainers would be appreciated.

I tried setting up the embedded server but that did not work.

```yaml
turn:
  enabled: true
  domain: <turn.myhost.com>
  tls_port: 3478
```

I also tried to set up external server with LiveKit but that did not work either.

```yaml

# WebRTC configuration
rtc:
  # # optional STUN servers for LiveKit clients to use. Clients will be configured to use these STUN servers automatically.
  # # by default LiveKit clients use Google's public STUN servers
  # stun_servers:
  #   - server1
  # # optional TURN servers for clients. This isn't necessary if using embedded TURN server (see below).
  turn_servers:
    - host: myhost.com
      port: 443
      # tls, tcp, or udp
      protocol: tls
      username: ""
      credential: ""
```

**Comment by michael-pisman** [comment]
I think I figured it out but I still need to do more testing.
For now I am using cloudflare TURN, I might try to use TURN server that comes with livekit later.

1. **Legacy Call**
   - You configure Turn as @kodxana showed. No additional configuration is required.
3. **Element-Call**
   - You need to configure Matrix RTC SFU
   - You need to configure your firewall/reverse proxy to forward RTC TCP/UDP traffic to rtc server.  
   - You need to enable experimental features.

I simply port-forwarded TCP on 30881 and UDP on 30882 using **metallb**. Also, experimental featured now seem to be enabled if mrtc is enabled, check pr #513 

## Synapse config via helm `values.yaml`

```yaml
ingress:
  className: traefik

certManager:
  clusterIssuer: letsencrypt

elementWeb:
  ingress:
    host: chat.matrix.mydomain.com

matrixAuthenticationService:
  ingress:
    host: account.matrix.mydomain.com
  additional:
    user-config.yaml:
      config: |
        upstream_oauth2:
          providers:
            - id: "my_app_id"
              human_name: GitHub
              brand_name: github
              ...

matrixRTC:
  ingress:
    host: mrtc.matrix.mydomain.com

serverName: 1cl.cc
synapse:
  ingress:
    host: matrix.1cl.cc
  additional:
    # Experimental featured seem to be enabled if mrtc is enabled, check pr #513  
    experimental_features:
      msc3266_enabled: true
      msc4222_enabled: true
    user-config.yaml:
      config: |
        turn_uris: 
        - "stun:stun.cloudflare.com:3478"
        - "stun:stun.cloudflare.com:53"
        - "turn:turn.cloudflare.com:3478?transport=udp"
        - "turn:turn.cloudflare.com:3478?transport=tcp"
        - "turns:turn.cloudflare.com:5349?transport=tcp"
        - "turn:turn.cloudflare.com:53?transport=udp"
        - "turn:turn.cloudflare.com:80?transport=tcp"
        - "turns:turn.cloudflare.com:443?transport=tcp"
        turn_username: "username"
        turn_password: "password"
        turn_user_lifetime: 31536000 # 1 year
        turn_allow_guests: true
```

## `matrix-matrix-rtc-sfu` Config Map 

For Element-Call you need to configure livekit mrtc. Edit `matrix-matrix-rtc-sfu` config Map 

```yaml
apiVersion: v1
data:
  config.yaml: |
    key_file: /conf/keys.yaml
    logging:
      json: false
      level: info
      pion_level: error
    port: 7880
    prometheus_port: 6789
    rtc:
      tcp_port: 30881  # TCP Port we will use (configure firewall)
      udp_port: 30882  # UDP Port we will use (configure firewall)
      use_external_ip: true
      use_ice_lite: false  # ICE Lite seemed to cause issues for my IPAD, so I turned it off
      stun_servers:  # Cloudflare STUN servers
      - "stun.cloudflare.com:3478"
      - "stun.cloudflare.com:53"
      turn_servers:  # Cloudflare TURN server
      - host: turn.cloudflare.com:3478?transport=udp
        port: 3478
        protocol: udp
        username: "username"
        credential: "password"
      - host: turn.cloudflare.com:3478?transport=tcp
        port: 3478
        protocol: tcp
        username: "username"
        credential: "password"
      - host: turn.cloudflare.com:5349?transport=tcp
        port: 5349
        protocol: tcp
        username: "username"
        credential: "password"
      - host: turn.cloudflare.com:443?transport=tcp
        port: 443
        protocol: tcp
        username: "username"
        credential: "password"
    turn:
      enabled: false
```
