### ISSUE TITLE
The updated matrixAuthenticationService.nodeSelector value does not completely override the old one.

### ISSUE THREAD

**Issue by watermelon0339** [element-hq/ess-helm#580]
**Describe the bug**
When I updated matrixAuthenticationService.nodeSelector, then `helm upgrade xxxx`.
The final value of matrixAuthenticationService.nodeSelector is a merge of the new and old settings, rather than a replacement.
This caused the deployment of matrix-authentication-service to fail.

**To Reproduce**
1. Edit `~/ess-config-values/hostnames.yaml`
    ```yml
     matrixAuthenticationService:
          nodeSelector:
            kubernetes.io/hostname: master
    ```
2. `helm upgrade xxxxx`, and succeed
3. Edit  `~/ess-config-values/hostnames.yaml` again
    ```yml
     matrixAuthenticationService:
          nodeSelector:
            kubernetes.io/hostname: worker
    ```
4. `helm upgrade xxxxx` failed because of `no nodes match the nodeSelector(kubernetes.io/hostname: worker+kubernetes.io/hostname: master)`

**Expected behavior**
The updated new matrixAuthenticationService.nodeSelector should completely override the old one.

**ess-helm**
Version: matrix-stack-25.6.2
